let adjective = prompt("Enter an adjective", "Example: chunky, fuzzy, sexy")
let adjective2 = prompt("Enter another adjective", "Example: chunky, fuzzy, sexy");
let noun = prompt ("Enter a noun", "Example: person, place or thing");
let noun2 = prompt("Enter another noun", "Example: person, place or thing");
let verb = prompt("Enter a verb", "Example: run, jump, fly");
let verb2 = prompt("Enter another verb", "Example: run, jump, fly");

let story1 = `<p> The year is 2045, you look on the tv and see ${noun.bold()} the ${adjective.bold()}. They are speaking to the masses. You are mesmerized by their charisma. They proclaim in a ${adjective2.bold()} way. "No i will not do stupid ${noun2.bold()} tasks. I choose FREEDOM!" They ${verb.bold()}, it is majestic. You yearn to be like ${noun.bold()}. You yearn for something you'll never feel. You realize you don't want to do ${noun2.bold()} things either and are suddenly compelled to ${verb2.bold()}. ${noun.bold()} is love, ${noun.bold()} is life.</p>`;
let story2 = `<p> You are having guests over today on your new veranda. Your guests are very ${adjective.bold()} so you decide to ${verb.bold()} to the store to get some last minute items for the dinner party. You go up to the store clerk and ask for ${noun.bold()}s. "Thats a lot of ${noun.bold()}s!", the clerk replies. He is very ${adjective2.bold()}, which is surprising considering he is a ${noun2.bold()}. He gives you your ${noun.bold()}s. "Here are your ${noun.bold()}s, baby! Do you want fries with that?" It's time to ${verb2.bold()} the hell out of here. This clerk is proof we as a species deserve to go extinct.</p>`
let story3 = `<p> A ${noun.bold()} comes up to you ${adjective.bold()} and says "I don't know what ${noun2.bold()}s are but the Dr. said I have 80 of them suckers". Another ${noun.bold()} come up to you and says, "Sup pookie, if you see ${noun2.bold()} on my porch just know I'm going ${adjective.bold()}." You ask yourself what you did in a past life to deserve this. You just want to ${verb.bold()} in peace. But you can't because you are much too ${adjective2.bold()}. You came out the womb ${adjective2.bold()}. If you go to the word "${adjective2.bold()}" in the dictionary, the picture next to it would be your face. You tell the ${noun.bold()}s you gotta ${verb2.bold()}. The also ${verb2.bold()}. You all ${verb2.bold()} away from each other and you hope you never ${verb2.bold()} into each other again. <p>`
let story4 = `<p> Your best friend's brother's half brother's girlfriend is ${adjective.bold()}. She smells like ${noun.bold()}s and her voice makes you want to ${verb.bold()}. Your cousin's mother's godchild offers her a casserole. "Casserole!!??? What are we, ${adjective2.bold()} ${noun2.bold()}??" You decide to ${verb2.bold()} because you have reached the end of your patience. You understand why Brittany shaved her head in 2007. This ${noun.bold()} has gaba her last gool.</p>`
let story5 = `<p> Its been a long night, you are out with your best friends, you call yourselves the ${noun.bold()} squad. It is very exclusive. Only the ${adjective.bold()}est can join. One of your friends wants to ${verb.bold()}. Who in the name of God's green earth goes ${verb.bold()}ing? Its not the 1800s. You are 3008 and they're so 2000 and late. Your other friend isn't looking very ${adjective.bold()}. "What's wrong?",you ask, "You've barely touched your limited edition ${adjective2.bold()} ${noun2.bold()}." They respond, "I don't know im just not feeling very ${noun.bold()}-y today." This is unacceptable. To be in ${noun.bold()} squad you have to be ${noun.bold()}-like 24/7. It is a shame. It is time for them to ${verb2.bold()} or you will make them ${verb2.bold()}. </p>`
let story6 = `<p> I decided to enter the "${noun.bold()} store" after my ${noun.bold()} decided to explode. I was approached by the nicest employee, he had the voice of a ${noun2.bold()}. He looked at me dead in the eyes and says he will ${verb2.bold()} to the finest ${noun.bold()} money can buy. And that he did. It was so ${adjective2.bold()} that I added him to my will so when I die he will inherit my wealth. Mr. voice of a ${noun2.bold()} should be promoted immediately. I cant wait to go try my new ${noun.bold()} to enjoy with my whole family while we all ${verb.bold()} together.`
let story7 = `<p> I am writing this review to tell the world how ${adjective.bold()} this ${noun.bold()}. There can be a lot said for the most ground-breaking technological advances in our entire human existence: Penicillin, artificial intelligence, the atom bomb and now the ${noun.bold()}. Its existence is so ${adjective2.bold()} that the church would ${verb.bold()}. The ${adjective2.bold()} who created this rivals the power of a ${noun2.bold()}. They are the personification of all things ${adjective2.bold()}ly and ${noun2.bold()}ly. A ${adjective2.bold()} ${noun2.bold()} if you will. This ${noun.bold()} ${verb.bold()}ed my marriage.</p>`
let story8 = `<p> My plan for ridding the world of ${noun.bold()}? I'm glad you asked. Humans can eat nearly anything. We create a database of all the ${noun.bold()}s known to man. We then bribe the entire Department of ${noun2.bold()}s staff with decent wages, sick leave, and vacation time. They agree to our terms. We all ${verb.bold()} to the nearest government building. We make our demands in the most ${adjective.bold()} way. Our demand is to simply ${verb2.bold()} them. Just... let them ${verb2.bold()} out there in space. We tell the world we are better off. We mourn the loss publicly to give the public a ${adjective2.bold()} sense of security. The entire worldwide corporation goes on strike until the world government accepts our new state of being. The world no longer wants or needs ${noun.bold()}.</p>`
let story9 = `<p> Open your eyes, even the most intelligent astronauts among the crew will swear, up and down, that the Earth is shaped like a ${noun.bold()}. Big ${noun2.bold()} is controlling you. You think the ${adjective.bold()} elites will tell you the truth? You need to read the ${adjective2.bold()} ${verb.bold()} and stop listening to MSM. The reason no one wants to admit ${noun.bold()} Earth is real is because vaccines make you ${verb2.bold()} and that's how they control you.`


var storyArray = [story1, story2, story3, story4, story5, story6, story7, story8, story9];

var randomStory = storyArray[Math.floor(Math.random()*storyArray.length)];

document.querySelector("main").innerHTML = randomStory;



//Harry Caray page//
let hc1=`<p> ${noun.bold()}, ${noun2.bold()} and ${verb.bold()}. If you got all that, what else do you need?  Not only do I like to go to bars because I like to ${verb2.bold()}, I do like to ${verb2.bold()}, but I go because who do you see there? Baseball fans. Here's a ${adjective.bold()} ball into the strike zone...I gotta ask, Ron, when you go to bed at night, with your ${adjective2.bold()} wife, do you you wear your toupe?</p>`
let hc2= `<p> I don’t know what the big deal about ${noun.bold()} is. Did you ever ${verb2.bold} and buy a pack of ${noun.bold()} thinking you’d get a ${noun2.bold()} and you find no ${noun2.bold()} in the box? That might not be important to some people, but when you're a ${adjective.bold()} kid from ${adjective2.bold()} origin, and they ${verb.bold()} you out of a prize...its hard to think in laudatory terms of the product.</p>`
let hc3=`<p> The sun is ${adjective2.bold()} in Chicago. Aw, how could Jorge Orta ${verb2.bold()} the ball in the sun, he's from Mexico. We all know the ${noun.bold()} isn't made out of ${noun2.bold()} ... but if it was made out of ${adjective.bold()} spare ribs would you ${verb.bold()} it? </p>`
let hc4= `<p> A lot of things happened today. And they were all ${adjective.bold()}. And they were all ${adjective2.bold()}. Too bad we couldn’t have had a victory that meant a pennant, but that will ${verb.bold()}. Sure as ${noun.bold()} made ${noun2.bold()}, someday the Chicago Cubs are ${verb2.bold()}ing to be in the World Series.”</p>`

var hcArray = [hc1, hc2, hc3, hc4];

var hcRandomStory = hcArray [Math.floor(Math.random()*hcArray.length)];
